version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/NodeCICD
   overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_instll.sh
      timeout: 300 
